/** Curated intake scenarios. These are preparatory pilot workflows, not permit determinations.
 * Every row defines an intent, a distinct question and a bounded example answer.
 */
export const DEFINITIONS = {
  food: [
    [
      "cafe",
      "Öppna café",
      ["öppna café", "öppna kafé", "starta café"],
      "Vilken mat och vilka drycker ska caféet servera?",
      "Smörgåsar, bakverk och kaffe",
    ],
    [
      "foodtruck",
      "Starta foodtruck",
      ["foodtruck", "matvagn"],
      "Var ska matvagnen stå och hur ordnas vatten och rengöring?",
      "En mobil matvagn med egen vattentank",
    ],
    [
      "bakery",
      "Starta bageri",
      ["bageri"],
      "Vad ska bakas och hur ska produkterna säljas?",
      "Bröd bakas på plats och säljs över disk",
    ],
    [
      "catering",
      "Starta catering",
      ["catering"],
      "Var tillagas maten och hur ska den transporteras?",
      "Mat från ett eget kök transporteras i kylbil",
    ],
    [
      "kiosk",
      "Öppna matkiosk",
      ["matkiosk"],
      "Vilka livsmedel ska hanteras i kiosken?",
      "Förpackade smörgåsar och varm korv",
    ],
    [
      "icecream",
      "Öppna glassförsäljning",
      ["glassförsäljning", "glasskiosk"],
      "Ska glassen tillverkas på plats eller köpas in färdig?",
      "Inköpt glass serveras i strut",
    ],
    [
      "foodshop",
      "Öppna livsmedelsbutik",
      ["livsmedelsbutik", "matbutik"],
      "Vilka typer av livsmedel och eventuell beredning planeras?",
      "Förpackade varor och ett kylt sortiment",
    ],
    [
      "foodproduction",
      "Starta livsmedelstillverkning",
      ["livsmedelstillverkning"],
      "Vad ska tillverkas och hur ska det levereras?",
      "Sylt i burkar levereras till lokala butiker",
    ],
    [
      "foodchange",
      "Ändra livsmedelsverksamhet",
      ["ändra livsmedelsverksamhet"],
      "Vad ändras jämfört med den befintliga verksamheten?",
      "Verksamheten utökas med tillagning av varm mat",
    ],
    [
      "foodclose",
      "Avsluta livsmedelsverksamhet",
      ["avsluta livsmedelsverksamhet", "stänga livsmedelsverksamhet"],
      "Vilken del av livsmedelsverksamheten upphör?",
      "All livsmedelshantering på platsen upphör",
    ],
  ],
  business: [
    [
      "shop",
      "Öppna butik",
      ["öppna butik", "öppna en butik", "starta butik", "klädbutik"],
      "Vilka varor ska butiken sälja?",
      "Kläder och skor",
    ],
    [
      "secondhand",
      "Öppna secondhandbutik",
      ["secondhandbutik"],
      "Vilka begagnade varor ska säljas och hur tas de emot?",
      "Kläder och möbler som lämnas in av privatpersoner",
    ],
    [
      "ecommerce",
      "Starta e-handel",
      ["e-handel", "webbutik"],
      "Vilka produkter säljs och var lagras varorna?",
      "Böcker säljs på nätet med lager i lokalen",
    ],
    [
      "hotel",
      "Öppna hotell",
      ["hotell", "vandrarhem"],
      "Vilken typ av boende och hur många rum planeras?",
      "Ett mindre hotell med tio rum",
    ],
    [
      "hairdresser",
      "Öppna frisörsalong",
      ["frisörsalong"],
      "Vilka behandlingar och installationer planeras?",
      "Klippning och hårtvätt vid två arbetsplatser",
    ],
    [
      "tattoo",
      "Öppna tatueringsstudio",
      ["tatueringsstudio"],
      "Vilka behandlingar och hygienrutiner planeras?",
      "Tatuering med engångsnålar och separata rengöringsytor",
    ],
    [
      "beauty",
      "Öppna skönhetssalong",
      ["skönhetssalong"],
      "Vilka behandlingar planeras och används stickande verktyg?",
      "Nagelvård och hudvård utan injektioner",
    ],
    [
      "gym",
      "Öppna gym",
      ["öppna gym", "öppna ett gym", "starta gym"],
      "Vilken träning och hur många besökare samtidigt planeras?",
      "Styrketräning för högst 30 besökare samtidigt",
    ],
    [
      "companyregistration",
      "Förbereda företagsregistrering",
      ["företagsregistrering"],
      "Gäller frågan F-skatt, moms, arbetsgivare eller en ändring?",
      "Registrering för F-skatt och moms",
    ],
  ],
  building: [
    [
      "newhouse",
      "Bygga enbostadshus",
      ["enbostadshus"],
      "Beskriv bostaden, antal våningar och ungefärlig höjd.",
      "Ett hus i ett plan, cirka fem meter högt",
    ],
    [
      "extension",
      "Bygga till huset",
      ["bygga till huset", "tillbyggnad"],
      "Vad ska tillbyggnaden användas till och hur ansluter den till huset?",
      "Ett extra bostadsrum mot trädgården",
    ],
    [
      "garage",
      "Bygga garage",
      ["garage"],
      "Ska garaget vara fristående och hur nära gränsen placeras det?",
      "Ett fristående garage fyra meter från tomtgränsen",
    ],
    [
      "carport",
      "Bygga carport",
      ["carport"],
      "Beskriv tak, antal platser och avstånd till tomtgräns.",
      "En öppen carport för två bilar",
    ],
    [
      "outbuilding",
      "Bygga komplementbyggnad",
      ["komplementbyggnad", "friggebod"],
      "Vad ska byggnaden användas till och var placeras den?",
      "Ett förråd bakom huvudbyggnaden",
    ],
    [
      "guesthouse",
      "Bygga komplementbostad",
      ["komplementbostad", "gästhus"],
      "Ska byggnaden innehålla en självständig bostad med kök och badrum?",
      "Ett gästhus med eget kök och badrum",
    ],
    [
      "conservatory",
      "Bygga uterum",
      ["uterum"],
      "Ska uterummet vara inglasat, uppvärmt och anslutet till huset?",
      "Ett inglasat, ouppvärmt uterum vid huset",
    ],
    [
      "deck",
      "Bygga altan",
      ["altan"],
      "Beskriv altanens höjd, placering och eventuella tak.",
      "En altan utan tak, 40 centimeter över marken",
    ],
    [
      "balcony",
      "Bygga balkong",
      ["balkong"],
      "På vilken fasad och våning ska balkongen byggas?",
      "En balkong på andra våningen mot gården",
    ],
    [
      "dormer",
      "Bygga takkupa",
      ["takkupa"],
      "Beskriv takkupan och hur den påverkar takets konstruktion.",
      "En mindre takkupa mot gatan",
    ],
    [
      "roof",
      "Ändra tak",
      ["ändra tak", "byta tak"],
      "Vilket material eller vilken form ska taket få?",
      "Tegeltaket ersätts med ett plåttak",
    ],
    [
      "facade",
      "Ändra fasad",
      ["ändra fasad", "byta fasad"],
      "Vilken del av fasaden och vilket material eller färg ändras?",
      "Gatufasaden får ljus puts",
    ],
    [
      "windows",
      "Ändra fönster",
      ["ändra fönster", "byta fönster"],
      "Beskriv förändringen av fönstrens storlek, placering eller utseende.",
      "Två fönster förstoras på gårdsfasaden",
    ],
    [
      "solar",
      "Installera solceller",
      ["solceller"],
      "Var placeras panelerna och följer de takets lutning?",
      "Panelerna följer det befintliga taket",
    ],
    [
      "chimney",
      "Installera eldstad",
      ["eldstad", "braskamin"],
      "Vilken eldstad och rökkanal ska installeras?",
      "En braskamin med en ny rökkanal genom taket",
    ],
    [
      "ventilation",
      "Ändra ventilation",
      ["ändra ventilation", "installera ventilation"],
      "Vilket ventilationssystem ändras och hur påverkas byggnaden?",
      "Ett mekaniskt till- och frånluftssystem installeras",
    ],
    [
      "structure",
      "Ändra bärande konstruktion",
      ["bärande konstruktion", "bärande vägg"],
      "Vilken bärande del ändras och vad ersätter den?",
      "En vägg ersätts med en dimensionerad balk",
    ],
    [
      "changeuse",
      "Ändra användning av lokal",
      ["ändra användning", "ändra lokalens användning"],
      "Vad används lokalen till i dag och vad ska den bli?",
      "En butikslokal ska bli kontor",
    ],
    [
      "splitdwelling",
      "Inreda ytterligare bostad",
      ["ytterligare bostad", "dela bostad"],
      "Hur ska den nya bostaden avskiljas och få entré, kök och hygienutrymme?",
      "En separat lägenhet inreds på övervåningen",
    ],
    [
      "demolition",
      "Riva byggnad",
      ["riva byggnad", "riva en byggnad", "rivning"],
      "Vilken byggnad eller byggnadsdel ska rivas?",
      "Ett äldre uthus på fastigheten",
    ],
    [
      "earthworks",
      "Ändra marknivå",
      ["ändra marknivå", "marknivå"],
      "Hur mycket ändras marknivån och hur hanteras vattenavrinning?",
      "Marken höjs cirka 40 centimeter på baksidan",
    ],
    [
      "wall",
      "Bygga mur eller plank",
      ["mur", "plank"],
      "Beskriv höjd, genomsiktlighet och placering vid gräns eller gata.",
      "Ett 1,8 meter högt plank mot grannen",
    ],
    [
      "buildsign",
      "Sätta upp fast skylt",
      ["fast skylt", "fasadskylt"],
      "Beskriv skyltens storlek, belysning och placering.",
      "En obelyst skylt på butikens fasad",
    ],
    [
      "greenhouse",
      "Bygga växthus",
      ["växthus"],
      "Hur stort och högt är växthuset och var placeras det?",
      "Ett växthus på tomtens baksida",
    ],
    [
      "buildingmap",
      "Beställa nybyggnadskarta",
      ["nybyggnadskarta"],
      "Vilken åtgärd ska kartan användas till?",
      "Underlag för ett nytt enbostadshus",
    ],
  ],
  events: [
    [
      "festival",
      "Arrangera festival",
      ["festival"],
      "Beskriv scener, aktiviteter, öppettider och publikflöden.",
      "Musik på en scen med entré och tydliga utgångar",
    ],
    [
      "concert",
      "Arrangera konsert",
      ["konsert"],
      "Beskriv scen, ljudanläggning och publikens placering.",
      "En mindre utomhuskonsert med sittande publik",
    ],
    [
      "market",
      "Arrangera marknad",
      ["marknad"],
      "Vad ska säljas och hur placeras försäljningsplatserna?",
      "Tjugo försäljningsplatser för hantverk",
    ],
    [
      "fleamarket",
      "Arrangera loppis",
      ["loppis"],
      "Beskriv antal försäljare och hur besökarna rör sig.",
      "En loppis med tio försäljare på en öppen gård",
    ],
    [
      "race",
      "Arrangera motionslopp",
      ["motionslopp", "löplopp"],
      "Beskriv sträckningen och hur vägar eller gångbanor berörs.",
      "Ett femkilometerslopp på gångbanor",
    ],
    [
      "demonstration",
      "Arrangera demonstration",
      ["demonstration"],
      "Beskriv samlingsplats, färdväg och planerade tider.",
      "En samling följd av en kort promenad",
    ],
    [
      "parade",
      "Arrangera parad",
      ["parad"],
      "Beskriv färdväg, fordon och hur trafiken påverkas.",
      "En parad till fots längs en angiven färdväg",
    ],
    [
      "sportsevent",
      "Arrangera idrottsevenemang",
      ["idrottsevenemang"],
      "Vilken idrott och vilka publik- och deltagarytor planeras?",
      "En turnering med avskild publikläktare",
    ],
    [
      "exhibition",
      "Arrangera utställning",
      ["utställning"],
      "Vad visas och hur ordnas tillträde och säkerhet?",
      "En öppen konstutställning med värdar på plats",
    ],
    [
      "event",
      "Arrangera evenemang",
      ["evenemang", "arrangemang"],
      "Vilken aktivitet ska genomföras och för vilka besökare?",
      "Ett öppet kvartersevenemang med aktiviteter",
    ],
  ],
  publicspace: [
    [
      "outdoorseating",
      "Anordna uteservering",
      ["anordna uteservering", "uteservering"],
      "Beskriv möblering, fria gångytor och serveringens avgränsning.",
      "Sex bord med fri passage längs trottoaren",
    ],
    [
      "container",
      "Placera container",
      ["container"],
      "Vad används containern till och hur påverkas gång- och körbanor?",
      "En byggcontainer med fri passage för gående",
    ],
    [
      "scaffolding",
      "Placera byggställning",
      ["byggställning"],
      "Beskriv ställningens utbredning och skydd för förbipasserande.",
      "En ställning med skyddad gångpassage",
    ],
    [
      "pavementsign",
      "Placera gatupratare",
      ["gatupratare"],
      "Beskriv placering och hur mycket fri gångyta som återstår.",
      "En skylt intill fasaden med bred fri gångyta",
    ],
    [
      "stall",
      "Ordna försäljningsstånd",
      ["försäljningsstånd"],
      "Vad ska säljas och vilken utrustning ska stå på platsen?",
      "Ett bord för hantverk utan el eller matlagning",
    ],
    [
      "filming",
      "Spela in film på offentlig plats",
      ["filminspelning", "spela in film"],
      "Beskriv inspelning, utrustning och behov av avspärrningar.",
      "En mindre inspelning utan stängda gångbanor",
    ],
    [
      "temporaryinstallation",
      "Placera tillfällig installation",
      ["tillfällig installation"],
      "Beskriv installationens material, förankring och publikåtkomst.",
      "En förankrad konstinstallation med säkerhetsavstånd",
    ],
    [
      "promotional",
      "Ordna informationskampanj på plats",
      ["informationskampanj"],
      "Beskriv bord, material och hur förbipasserande påverkas.",
      "Ett informationsbord utan högtalare",
    ],
    [
      "constructionstorage",
      "Förvara byggmaterial på gata",
      ["byggmaterial på gata", "byggbelamring"],
      "Vilket material lagras och hur säkras framkomligheten?",
      "Pallar med byggmaterial inom en inhägnad yta",
    ],
    [
      "mobilevending",
      "Ordna mobil försäljning",
      ["mobil försäljning"],
      "Vilka varor säljs, med vilken utrustning och på vilka platser?",
      "En mobil vagn med förpackade varor",
    ],
  ],
  environment: [
    [
      "heatpump",
      "Installera värmepump",
      ["värmepump", "bergvärme"],
      "Vilken värmepump och eventuell borrning eller markledning planeras?",
      "En bergvärmepump med ett borrhål",
    ],
    [
      "smallsewage",
      "Anlägga enskilt avlopp",
      ["enskilt avlopp", "små avloppsanläggningar"],
      "Beskriv avloppslösning, belastning och möjlig utsläppspunkt.",
      "En anläggning för ett hushåll med efterpolering",
    ],
    [
      "sewagechange",
      "Ändra avloppsanläggning",
      ["ändra avloppsanläggning"],
      "Vad ändras i den befintliga avloppsanläggningen?",
      "Reningssteget byts ut men platsen behålls",
    ],
    [
      "oiltank",
      "Installera eller avveckla cistern",
      ["cistern"],
      "Gäller åtgärden installation, ändring eller avveckling och vilket innehåll?",
      "En tidigare oljecistern ska tas ur bruk",
    ],
    [
      "noise",
      "Anmäla bullerstörning",
      ["bullerstörning", "anmäla buller"],
      "Beskriv bullerkällan, tiderna och var störningen märks.",
      "Återkommande maskinbuller på kvällstid",
    ],
    [
      "odour",
      "Anmäla luktstörning",
      ["luktstörning"],
      "Beskriv luktens källa, karaktär och när den förekommer.",
      "Stark lukt från en närliggande verksamhet på kvällar",
    ],
    [
      "litter",
      "Anmäla nedskräpning",
      ["nedskräpning"],
      "Beskriv avfallet, mängden och platsens åtkomlighet.",
      "Säckar och byggavfall har lämnats intill en väg",
    ],
    [
      "hazardouswaste",
      "Fråga om farligt avfall",
      ["farligt avfall"],
      "Vilket avfall gäller frågan och kommer det från hushåll eller verksamhet?",
      "Spillolja från en mindre verksamhet",
    ],
    [
      "businesswaste",
      "Fråga om verksamhetsavfall",
      ["verksamhetsavfall"],
      "Vilka avfallsslag och ungefärliga mängder uppstår?",
      "Wellpapp och restavfall från en butik",
    ],
    [
      "environmentalbusiness",
      "Förbereda miljöfråga för verksamhet",
      ["miljöfråga för verksamhet"],
      "Beskriv verksamheten, processer och möjliga utsläpp eller störningar.",
      "En mindre verkstad med tvätt och kemikaliehantering",
    ],
  ],
  waterwaste: [
    [
      "waterconnection",
      "Ansluta fastighet till VA",
      ["ansluta fastighet till va", "va-anslutning"],
      "Vilka anslutningar behövs och finns en befintlig förbindelsepunkt?",
      "Vatten och avlopp till en tidigare oansluten fastighet",
    ],
    [
      "waterchange",
      "Ändra VA-anslutning",
      ["ändra va-anslutning"],
      "Vad ska ändras i den befintliga anslutningen?",
      "En ytterligare byggnad ska anslutas inom fastigheten",
    ],
    [
      "watermeter",
      "Fråga om vattenmätare",
      ["vattenmätare"],
      "Gäller frågan placering, byte eller avläsning av mätaren?",
      "Platsen för mätaren behöver flyttas",
    ],
    [
      "waterleak",
      "Rapportera misstänkt vattenläcka",
      ["vattenläcka"],
      "Var märks läckan och gäller den gatan eller den egna fastigheten?",
      "Vatten syns på gatan nära fastighetsgränsen",
    ],
    [
      "waterquality",
      "Fråga om dricksvattenkvalitet",
      ["dricksvattenkvalitet"],
      "Beskriv vad som förändrats och om fler tappställen är berörda.",
      "Vattnet har en ovanlig färg vid flera kranar",
    ],
    [
      "stormwater",
      "Fråga om dagvatten",
      ["dagvatten"],
      "Beskriv hur regnvatten avleds och vilket problem som uppstår.",
      "Regnvatten samlas vid fastighetsgränsen",
    ],
    [
      "wastesubscription",
      "Ändra avfallsabonnemang",
      ["avfallsabonnemang"],
      "Vilken ändring av kärl eller hämtning önskas?",
      "Ett mindre kärl och ändrad hämtningsfrekvens",
    ],
    [
      "missedcollection",
      "Rapportera utebliven sophämtning",
      ["utebliven sophämtning"],
      "Vilket kärl lämnades och vilken hämtningsdag gäller det?",
      "Restavfallskärlet lämnades vid den senaste hämtningen",
    ],
    [
      "wastecontainer",
      "Byta avfallskärl",
      ["avfallskärl"],
      "Är kärlet skadat eller önskas annan storlek?",
      "Kärlets lock är trasigt och behöver bytas",
    ],
    [
      "compost",
      "Fråga om hemkompostering",
      ["hemkompostering"],
      "Vad ska komposteras och vilken behållare och placering planeras?",
      "Matavfall i en sluten, skadedjurssäker behållare",
    ],
  ],
  traffic: [
    [
      "excavation",
      "Gräva i kommunal mark",
      ["gräva i kommunal mark", "grävtillstånd"],
      "Beskriv schaktets sträckning, syfte och återställning.",
      "En ledning läggs längs en kort sträcka i gatan",
    ],
    [
      "trafficplan",
      "Förbereda trafikanordningsplan",
      ["trafikanordningsplan", "ta-plan"],
      "Beskriv arbete, avstängning och hur gående och cyklister passerar.",
      "Ett vägarbete med en säker omledd gångväg",
    ],
    [
      "transport",
      "Fråga om transportdispens",
      ["transportdispens"],
      "Beskriv transportens mått, vikt och önskad färdväg.",
      "En bred transport med angiven färdväg genom kommunen",
    ],
    [
      "lighting",
      "Felanmäl gatubelysning",
      ["gatubelysning"],
      "Beskriv felet och ange stolpnummer om det finns.",
      "Lampan är släckt, stolpnummer 12345",
    ],
    [
      "pothole",
      "Felanmäl skadad gata",
      ["skadad gata", "potthål"],
      "Beskriv skadan och hur trafikanter påverkas.",
      "Ett djupt hål nära kanten av körbanan",
    ],
    [
      "cycling",
      "Felanmäl gång- eller cykelbana",
      ["cykelbana", "gångbana"],
      "Beskriv hindret eller skadan och den exakta platsen.",
      "En upphöjd kant mitt på cykelbanan",
    ],
    [
      "roadgrant",
      "Fråga om bidrag till enskild väg",
      ["enskild väg"],
      "Beskriv vägen, användningen och det stöd som efterfrågas.",
      "Underhåll av en väg som är öppen för allmän trafik",
    ],
  ],
  education: [
    [
      "adultbasic",
      "Planera grundläggande vuxenstudier",
      ["grundläggande vuxenstudier"],
      "Vilka ämnen och vilken studieomfattning är aktuella?",
      "Svenska och matematik på deltid",
    ],
    [
      "adultvocational",
      "Planera yrkesutbildning för vuxna",
      ["yrkesutbildning för vuxna", "yrkesvux"],
      "Vilken yrkesinriktning och önskad studieform gäller frågan?",
      "En yrkesutbildning inom bygg på heltid",
    ],
    [
      "counselling",
      "Boka studie- och yrkesvägledning",
      ["studie- och yrkesvägledning", "studievägledning"],
      "Vilken utbildnings- eller yrkesfråga vill du få vägledning om?",
      "Val av vuxenutbildning och möjlig studieplan",
    ],
    [
      "schooltransport",
      "Förbereda fråga om skolskjuts",
      ["skolskjuts"],
      "Vilken sträcka och praktisk förutsättning behöver bedömas?",
      "Resvägen mellan bostadsområdet och skolan; inga elevuppgifter",
    ],
  ],
  associations: [
    [
      "association",
      "Registrera föreningsintresse",
      ["föreningsintresse", "starta förening"],
      "Beskriv föreningens ändamål och vilken kommunal kontakt som behövs.",
      "En ideell förening för lokala kulturaktiviteter",
    ],
    [
      "facility",
      "Boka idrottsanläggning",
      ["idrottsanläggning", "boka sporthall"],
      "Vilken aktivitet, lokaltyp och tider behövs?",
      "Träning i en sporthall två kvällar i veckan",
    ],
    [
      "associationgrant",
      "Förbereda fråga om föreningsbidrag",
      ["föreningsbidrag"],
      "Vilken verksamhet eller aktivitet ska stödet avse?",
      "Öppen ungdomsverksamhet i en ideell förening",
    ],
    [
      "culturegrant",
      "Förbereda fråga om kulturstöd",
      ["kulturstöd"],
      "Beskriv kulturaktiviteten, målgruppen och användningen av stödet.",
      "En lokal konstverkstad öppen för allmänheten",
    ],
  ],
};
