/** Versioned scenario specification. Routing proposals, never automatic legal decisions. */
export const RESTAURANT = {
  id: "restaurant.trelleborg",
  version: "1.0.0",
  title: "Öppna restaurang i Trelleborg",
  jurisdiction: "SE-1287",
  lifecycle: "pilot",
  reviewedAt: "2026-10-08",
  scope:
    "En ny, stadigvarande restaurang på en angiven plats i Trelleborg. Högst 500 gäster. Inga personuppgifter, ägarprövningar eller riktiga ansökningar i pilotmiljön.",
  sources: {
    tax: {
      title: "Skatteverket · Starta och registrera företag",
      url: "https://www.skatteverket.se/foretag/drivaforetag/startaochregistrera.4.58d555751259e4d661680006123.html",
      checkedAt: "2026-10-08",
    },
    food: {
      title: "Trelleborg · Registrera livsmedelsverksamhet",
      url: "https://eservice.trelleborg.se/VEFOLI",
      checkedAt: "2026-10-08",
    },
    alcohol: {
      title: "Trelleborg · Serveringstillstånd för alkohol",
      url: "https://www.trelleborg.se/naringsliv-arbete/tillstand-regler-och-tillsyn/serveringstillstand-for-alkohol/",
      checkedAt: "2026-10-08",
    },
    building: {
      title: "Trelleborg · Ändrad användning",
      url: "https://www.trelleborg.se/bygga-bo-miljo/bygga-nytt-andra-eller-riva/vad-vill-du-bygga/andrad-anvandning/",
      checkedAt: "2026-10-08",
    },
    public_space: {
      title: "Polisen · Använda offentlig plats",
      url: "https://polisen.se/tjanster-tillstand/tillstand-ansok/offentlig-plats/",
      checkedAt: "2026-10-08",
    },
  },
  authorities: {
    "skatteverket.registration": {
      name: "Skatteverket",
      organisation: "Skatteverket",
      short: "SK",
      service: "Företagsregistrering",
    },
    "trelleborg.food": {
      name: "Miljöenheten",
      organisation: "Trelleborgs kommun",
      short: "MI",
      service: "Livsmedel",
    },
    "trelleborg.alcohol": {
      name: "Tillståndsenheten",
      organisation: "Trelleborgs kommun",
      short: "TI",
      service: "Alkoholservering",
    },
    "trelleborg.building": {
      name: "Bygglovsavdelningen",
      organisation: "Trelleborgs kommun",
      short: "BY",
      service: "Lokalens användning",
    },
    "police.public_space": {
      name: "Polisen",
      organisation: "Polismyndigheten",
      short: "PO",
      service: "Offentlig plats",
    },
    "trelleborg.land": {
      name: "Mark & offentlig miljö",
      organisation: "Trelleborgs kommun",
      short: "MA",
      service: "Platsens förutsättningar",
    },
    "trelleborg.fire": {
      name: "Räddningstjänsten",
      organisation: "Trelleborgs kommun",
      short: "RÄ",
      service: "Brandskyddsunderlag",
    },
  },
  fields: {
    tax_registration_needed: {
      label: "Företagsregistrering behövs",
      type: "boolean",
      priority: 60,
      required: true,
      question:
        "Behöver ni registrera eller ändra F-skatt, moms eller arbetsgivarregistrering?",
      help: "Ange om du vill ha hjälp med en registreringsfråga. ÖPPNA avgör inte automatiskt din skattskyldighet.",
    },
    address: {
      label: "Adress",
      type: "text",
      min: 5,
      max: 160,
      priority: 100,
      required: true,
      question: "Var ska restaurangen ligga?",
      help: "Ange gatuadress i Trelleborgs kommun. Ingen registerkontroll görs ännu.",
      placeholder: "Storgatan 12, Trelleborg",
    },
    municipality: {
      label: "Kommun",
      type: "enum",
      options: ["Trelleborg"],
      priority: 110,
      required: true,
      question: "Ligger restaurangen i Trelleborgs kommun?",
      help: "Första scenariot är avgränsat till Trelleborg.",
    },
    alcohol: {
      label: "Alkoholservering",
      type: "boolean",
      priority: 99,
      required: true,
      question: "Ska ni servera alkohol?",
      help: "Svaret avgör om en fråga om serveringstillstånd behöver förberedas.",
    },
    current_use: {
      label: "Lokalens nuvarande användning",
      type: "enum",
      options: ["Restaurang", "Butik", "Kontor", "Lager", "Bostad", "Annat"],
      priority: 95,
      required: true,
      question: "Vad används lokalen till i dag?",
      help: "En ändrad användning kan behöva prövas även utan ombyggnad.",
    },
    building_changes: {
      label: "Ändringar av lokalen",
      type: "boolean",
      priority: 91,
      required: true,
      question: "Ska ni ändra ventilation, brandskydd eller bärande delar?",
      help: "Sådana ändringar behöver bedömas separat från verksamhetens öppnande.",
    },
    outdoor: {
      label: "Uteservering",
      type: "boolean",
      priority: 90,
      required: true,
      question: "Vill ni ha uteservering?",
      help: "Platsens förutsättningar styr vilka ytterligare frågor som behövs.",
    },
    public_land: {
      label: "Offentlig plats",
      type: "boolean",
      priority: 89,
      required: true,
      when: { field: "outdoor", eq: true },
      question: "Ska uteserveringen ligga på offentlig plats?",
      help: "Det kan till exempel vara en trottoar eller ett torg. Är du osäker, välj ”Vet inte”.",
    },
    outdoor_area: {
      label: "Uteserveringens yta",
      type: "number",
      min: 1,
      max: 1000,
      unit: "m²",
      priority: 75,
      required: true,
      when: { field: "outdoor", eq: true },
      question: "Ungefär hur stor ska uteserveringen vara?",
      help: "Ange ytan i kvadratmeter. Den ingår i underlaget för platsbedömningen.",
    },
    capacity: {
      label: "Antal gäster",
      type: "number",
      min: 1,
      max: 500,
      unit: "gäster",
      priority: 85,
      required: true,
      question: "Hur många gäster ska restaurangen rymma?",
      help: "Ange högsta planerade antalet samtidigt, inklusive uteservering.",
    },
    food_preparation: {
      label: "Matberedning",
      type: "enum",
      options: [
        "Tillagning på plats",
        "Uppvärmning av färdig mat",
        "Endast servering av färdig mat",
      ],
      priority: 70,
      required: true,
      question: "Hur ska ni hantera maten?",
      help: "Miljöenheten behöver förstå verksamhetens livsmedelshantering.",
    },
    portions: {
      label: "Portioner per dag",
      type: "number",
      min: 1,
      max: 10000,
      unit: "portioner/dag",
      priority: 65,
      required: true,
      question: "Ungefär hur många portioner räknar ni med per dag?",
      help: "Antalet gäster samtidigt och verksamhetens omfattning är olika uppgifter.",
    },
    opening_date: {
      label: "Önskad start",
      type: "date",
      priority: 40,
      required: true,
      question: "När vill ni öppna?",
      help: "Datumet används för planering. ÖPPNA lovar ingen handläggningstid.",
    },
    cuisine: {
      label: "Inriktning",
      type: "text",
      min: 2,
      max: 60,
      priority: 10,
      required: false,
    },
  },
  rules: [
    {
      id: "tax_registration",
      authority: "skatteverket.registration",
      title: "Företagsregistrering",
      when: { field: "tax_registration_needed", eq: true },
      fields: ["municipality", "tax_registration_needed", "opening_date"],
      sources: ["tax"],
      question:
        "Vilken registrering eller ändring behöver företaget hjälp att förbereda inför verksamhetsstarten?",
      reason: "Företagaren har angett behov av registreringshjälp.",
      kind: "human_assessment",
      limits:
        "Företagsform, identitet, ekonomiska förutsättningar och aktuell registerstatus saknas. Inga beslut om F-skatt, moms eller arbetsgivarregistrering fattas här.",
    },
    {
      id: "food_registration",
      authority: "trelleborg.food",
      title: "Registrering av livsmedelsverksamhet",
      when: { always: true },
      fields: [
        "address",
        "municipality",
        "food_preparation",
        "portions",
        "opening_date",
        "cuisine",
      ],
      sources: ["food"],
      question:
        "Är verksamhetens plats och omfattning tillräckligt beskrivna för att gå vidare med livsmedelsregistreringen?",
      reason: "Restaurangen ska hantera och servera livsmedel.",
      kind: "registration",
      limits:
        "Företrädare, organisationsnummer, kontaktuppgifter och fullständig anmälan behöver tillföras genom godkänd identitets- och myndighetsanslutning.",
    },
    {
      id: "alcohol_assessment",
      authority: "trelleborg.alcohol",
      title: "Alkoholservering",
      when: { field: "alcohol", eq: true },
      fields: [
        "address",
        "municipality",
        "alcohol",
        "capacity",
        "outdoor",
        "opening_date",
      ],
      sources: ["alcohol"],
      question:
        "Vilka ytterligare uppgifter och prövningar krävs för den planerade alkoholserveringen?",
      reason: "Alkohol ska serveras i den planerade verksamheten.",
      kind: "permit_assessment",
      limits:
        "Personlig och ekonomisk lämplighet, finansiering, rätt till lokalen och kunskapsprov hanteras inte automatiskt i denna pilot.",
    },
    {
      id: "building_assessment",
      authority: "trelleborg.building",
      title: "Lokalens användning och ändringar",
      when: {
        any: [
          { field: "current_use", neq: "Restaurang" },
          { field: "building_changes", eq: true },
        ],
      },
      fields: [
        "address",
        "municipality",
        "current_use",
        "building_changes",
        "capacity",
        "outdoor",
        "opening_date",
      ],
      sources: ["building"],
      question:
        "Behöver restaurangens användning eller planerade ändringar prövas genom lov eller anmälan?",
      reason:
        "Den tidigare användningen skiljer sig från restaurang, eller ändringar planeras.",
      kind: "human_assessment",
      limits:
        "Detaljplan, kulturvärden och tekniskt underlag behöver kontrolleras av behörig handläggare. Ingen automatisk slutsats om lovplikt dras.",
    },
    {
      id: "public_space",
      authority: "police.public_space",
      title: "Uteservering på offentlig plats",
      when: {
        all: [
          { field: "outdoor", eq: true },
          { field: "public_land", eq: true },
        ],
      },
      fields: [
        "address",
        "municipality",
        "outdoor",
        "public_land",
        "outdoor_area",
        "opening_date",
      ],
      sources: ["public_space"],
      question:
        "Behöver användningen av platsen tillstånd, och vilka uppgifter eller villkor behövs för prövningen?",
      reason: "Uteserveringen föreslås använda offentlig plats.",
      kind: "permit_assessment",
      limits:
        "Platsens rättsliga status, detaljplaneläge, utformning och ansökningsunderlag måste kontrolleras. Avgift och tillstånd hanteras hos Polisen.",
    },
    {
      id: "land_consultation",
      authority: "trelleborg.land",
      title: "Platsbedömning för uteservering",
      when: {
        all: [
          { field: "outdoor", eq: true },
          { field: "public_land", eq: true },
        ],
      },
      fields: ["address", "outdoor_area", "capacity", "opening_date"],
      sources: ["public_space"],
      question:
        "Vilka förutsättningar behöver beaktas för passage, tillgänglighet och användning av den föreslagna platsen?",
      reason:
        "Kommunala synpunkter kan behövas vid användning av offentlig plats.",
      kind: "consultation",
      limits:
        "Detta är ett förberett yttrandeunderlag. En formell remiss från Polisen är inte automatiskt skapad.",
    },
    {
      id: "fire_consultation",
      authority: "trelleborg.fire",
      title: "Brandskyddsunderlag",
      when: {
        any: [
          { field: "alcohol", eq: true },
          { field: "building_changes", eq: true },
          { field: "current_use", neq: "Restaurang" },
        ],
      },
      fields: [
        "address",
        "current_use",
        "capacity",
        "building_changes",
        "outdoor",
      ],
      sources: ["alcohol", "building"],
      question:
        "Behöver brandskyddsunderlaget kompletteras inför den planerade verksamheten eller lokaländringen?",
      reason:
        "Brandsäkerhet är relevant för serveringstillstånd och vissa ändringar av lokalen.",
      kind: "consultation",
      limits:
        "Ingen generell brandskyddsdispens eller automatisk brandinspektion skapas. Rätt ansvarig aktör och eventuell remissväg måste bekräftas.",
    },
  ],
};
